package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Optional;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/search") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private BaanRepository baanRepository;

	
	@GetMapping(path="/boat/all")
	public @ResponseBody Iterable<Baan> getAllUsers() {
		// This returns a JSON or XML with the users
		return baanRepository.findAll();
	}

	@GetMapping("/boat/{id}")
	public Baan getBoatById(@PathVariable(value = "id") int boatImo) {
		return baanRepository.findById(boatImo)
				.orElseThrow(() -> new BoatNotFoundException(boatImo));
	}
}
